#!/bin/bash

source "$(dirname $0)/variables"

rsync -arzP --info=progress2 ./*.py ./environment.yml ./models ./util ./hyper_grids $INSTANCE:~/squad
rsync -arzP --info=progress2 --exclude "glove.840B.300d*" ./data/ $INSTANCE:~/squad/data
