#!/bin/bash

session="tensorboard"
window="Tensorboard"
tmux new-session -d -s $session
tmux rename-window -t 0 $window
tmux send-keys -t $window 'conda activate squad' C-m
tmux send-keys -t $window 'tensorboard --logdir squad/save' C-m
